#include <cmath>
#include <vector>
#include <utility>
#include <limits>
#include <iostream>
#include <ros/ros.h>
#include <fstream>
#include <sstream>
#include <string>
#include <geometry_msgs/PointStamped.h>
#include <tf2/LinearMath/Quaternion.h>
#include <tf2/LinearMath/Matrix3x3.h>
#include <tf2_msgs/TFMessage.h>
#include <morai_msgs/CtrlCmd.h>